### ISSUE TITLE
Cambiar publicidad

### ISSUE THREAD

**Issue by mentorrolling** [mentorrolling/superfriends-app-103i#2]
La publicidad de Comicon no va, ahora tenemos que cargar la de RollingCode School.
Dejo imagen de la publicidad que hay que sacar.

![image](https://github.com/mentorrolling/superfriends-app-103i/assets/68254100/951b7d28-9a74-4a95-9a45-a5480e87df8b)

**Comment by pmarino2013** [comment]
Se cambió la publicidad
